// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartVideoCallApp.Data;

#nullable disable

namespace SmartVideoCallApp.Migrations
{
    [DbContext(typeof(AppSignDbContext))]
    partial class AppSignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmartVideoCallApp.Data.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("MeetingRoomId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("MeetingRoomId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("SmartVideoCallApp.Data.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MeetingRoomId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("MeetingRoomId", "SentAtUtc");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("SmartVideoCallApp.Data.Entities.MeetingRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("HostUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HostUserId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.ToTable("MeetingRooms");
                });

            modelBuilder.Entity("SmartVideoCallApp.Data.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("SmartVideoCallApp.Data.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("SmartVideoCallApp.Data.Entities.ActivityLog", b =>
                {
                    b.HasOne("SmartVideoCallApp.Data.Entities.MeetingRoom", "MeetingRoom")
                        .WithMany("Activities")
                        .HasForeignKey("MeetingRoomId");

                    b.HasOne("SmartVideoCallApp.Data.Entities.UserAccount", "UserAccount")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserAccountId");

                    b.Navigation("MeetingRoom");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("SmartVideoCallApp.Data.Entities.ChatMessage", b =>
                {
                    b.HasOne("SmartVideoCallApp.Data.Entities.MeetingRoom", "MeetingRoom")
                        .WithMany("Messages")
                        .HasForeignKey("MeetingRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartVideoCallApp.Data.Entities.UserAccount", "SenderUser")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingRoom");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("SmartVideoCallApp.Data.Entities.MeetingRoom", b =>
                {
                    b.HasOne("SmartVideoCallApp.Data.Entities.UserAccount", "HostUser")
                        .WithMany("HostedRooms")
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartVideoCallApp.Data.Entities.Organization", "Organization")
                        .WithMany("Rooms")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("HostUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartVideoCallApp.Data.Entities.UserAccount", b =>
                {
                    b.HasOne("SmartVideoCallApp.Data.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartVideoCallApp.Data.Entities.MeetingRoom", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SmartVideoCallApp.Data.Entities.Organization", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartVideoCallApp.Data.Entities.UserAccount", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("HostedRooms");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
